#!/bin/bash


monitoringProcess() {
    local _sleepTime=$1
    while true
    do
        top -bn 1 | awk 'NR==8' >> /var/log/monitoring-process/logs.log
        sleep $_sleepTime
        echo "ciao"
    done
}


_sleepTime=$1
monitoringProcess $_sleepTime